version: '3'
services:
  server:
    image: golang:1.20
    restart: always
    depends_on:
    - nats
    volumes:
    - .:/app
    - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run main.go
    environment:
      NATS_URL: "nats://mytoken@nats:4222"

  nats:
    image: nats:2
    ports:
      - "4222:4222"
    restart: always
    command:
      - -auth
      - mytoken
      - -js
